//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exam()
        {
            this.ExamEnrollments = new HashSet<ExamEnrollment>();
            this.QuestionInExams = new HashSet<QuestionInExam>();
            this.StudentRespones = new HashSet<StudentRespone>();
        }
    
        public string ExamID { get; set; }
        public string ExamTitle { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<int> NumberOfQuestion { get; set; }
        public Nullable<double> MarkPerQuestion { get; set; }
        public Nullable<byte> examTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamEnrollment> ExamEnrollments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionInExam> QuestionInExams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentRespone> StudentRespones { get; set; }
    }
}
