//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamEnrollment
    {
        public int ExamNumber { get; set; }
        public Nullable<System.DateTime> AttendDate { get; set; }
        public string ExamID { get; set; }
        public string StudentUserName { get; set; }
        public Nullable<double> Mark { get; set; }
    
        public virtual Exam Exam { get; set; }
        public virtual Student Student { get; set; }
    }
}
