//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExaminationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExaminationSystemEntities : DbContext
    {
        public ExaminationSystemEntities()
            : base("name=ExaminationSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Administrator> Administrators { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<ExamEnrollment> ExamEnrollments { get; set; }
        public virtual DbSet<Exam> Exams { get; set; }
        public virtual DbSet<QuestionChoice> QuestionChoices { get; set; }
        public virtual DbSet<QuestionCorrectAnswer> QuestionCorrectAnswers { get; set; }
        public virtual DbSet<QuestionDisplayOrder> QuestionDisplayOrders { get; set; }
        public virtual DbSet<QuestionInExam> QuestionInExams { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<StudentRespone> StudentRespones { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
    }
}
